#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,walltime=0:30:00

segmentation=`jq -r '.segmentation' config.json`
t1=`jq -r '.t1' config.json`
step_size=`jq -r '.step_size' config.json`

echo "Convert WMC to trk."
singularity exec docker://brainlife/mcr:neurodebian1604-r2017a bash -c "./compiled/afqConverter"
ret=$?
if [ ! $ret -eq 0 ]; then
	echo "Computation failed"
	echo $ret > finished
	exit $ret
fi

mkdir output_trk
mv *.trk output_trk

if [ ! $step_size = "null" ]; then
	echo "Resampling segentation..."
	mkdir output_trk_res
	singularity exec -e docker://brainlife/dipy:0.14 python ./resampling_segmentation.py -trk_dir output_trk -t1 $t1 -step_size $step_size -out_dir output_trk_res

if [ -z "$(ls -A -- "output_trk_res")" ]; then 
    echo "Resampling failed."
    exit 1
else 
    echo "Resampling done."   
fi

echo "Complete"
